In [1]:
import numpy as np

### rand & randn & randint



### rand
**random.rand():** 0-1 aralığında uniform dağılıma sahip random float sayılar üretir.



In [2]:
np.random.rand()

0.8032207246874591

In [3]:
np.random.rand(2,3)

array([[0.29955594, 0.86949805, 0.33481398],
       [0.67779396, 0.27759287, 0.39089678]])

### randn

**random.randn():** ortalama değeri 0 ve standart sapması 1 olan normal dağılıma sahip rastgele sayılar üretir.



In [4]:
np.random.randn()

-1.389792698047066

In [5]:
np.random.randn(3,4)

array([[-1.68189632,  0.2658859 ,  1.03786878,  0.80546224],
       [ 0.44323734,  1.13257675, -0.24251167, -0.11354469],
       [ 1.05466283,  1.54346911, -0.80976316,  0.48318302]])

In [8]:
np.random.randn(300,400).mean() #ortalama sıfıra oldukça yakın.

0.0020501461426382407

In [7]:
np.random.randn(300,400).std() #std 1'e oldukça yakın.

0.9986523582025557

### randint

**random.randint():** belirtilen aralıkta rastgele tamsayılar üretir. Bitiş dahil değil.

In [9]:
np.random.randint(1,100)

80

In [10]:
np.random.randint(1,100,7)

array([70, 35, 13, 29, 89, 99, 77])